### PR TITLE
Extend rules examples - Fixes #16

### LINKED ISSUE #16: Add additional usage examples to the filetypes.py documentation
Add some additional comments to the `filetypes.py` file that shows the user how to

- use callables as an action
- use the action.SkipRecure action
- use the action.Skip action
- use numerical matching groups in their patterns
- use named matching groups in their patterns

### PR DESCRIPTION
**Pull request by astrikos**
Is this what you were thinking? I skipped to add example for callables since there is no example yet. 
I guess as soon as #19 is implemented (I might give it a try later) we can add it then.

### CODE REVIEW

**Comment by astrikos** [comment]
hm yeah that's not going to work easily. The way you do exec now in [rules.py](https://github.com/astrikos/pysorter/blob/master/pysorter/rules.py#L73), there shouldn't be any import inside [filetype.py](https://github.com/astrikos/pysorter/blob/master/pysorter/filetypes.py) file.
One possibility would be to have callables like strings[1] and and import them using `importlib.import_module`. I could give it a try see if it works if you think is a way to go. 
Or maybe you have another solution and I just don't see it :)

[1] (r'\.cer$', 'action.Skip')

**Comment by chriscz** [comment]
Hey @astrikos, 

Would doing an absolute import work instead, or is there a problem with that?. We can assume that even developers should have done a `pip install -e .`

However it may break when doing tests so maybe a hack along the lines of:
```python
try:
    from pysorter import action
except ImportError:
    from . import action
```

What do you think?

**Comment by astrikos** [comment]
Hi @chriscz, using absolutely import seems to work, it just breaks consistency throughout the project, which seems to use relative imports ([example1](https://github.com/chriscz/pysorter/blob/master/pysorter/rules.py#L8), [example2](https://github.com/chriscz/pysorter/blob/master/pysorter/core/pysorter.py#L15)).
But since it works there is no real need to complicate it more. I will add a comment above import to make sure next one knows that is has to use absolutely imports in this file.
Do you want me to squash all commits to one or you prefer to have two different for import and for comment?

**Comment by chriscz** [comment]
trading consistency for simplicity here should be fine, since this file (will eventually) be viewed and edited by users of pysorter, so it makes sense.  A comment would be quite fitting here.

You are free to squash the commits, I haven't developed a preference yet ;). In addition could you rebase on the latest develop branch?

Thanks for contributing, I really appreciate it!

**Comment by astrikos** [comment]
okay, squashed everything in one commit and rebase develop branch.

**Pull request closed without merging**
