### PR TITLE
implementation of issue_14: dry run flag

### PR DESCRIPTION
**Pull request by toondegryse**

### CODE REVIEW

**Comment by toondegryse** [comment]
If you could assist me to run the test .. :)

**Comment by chriscz** [comment]
To run the tests locally you can do `python setup.py test`. 
To see why the tests failed you can click the [Details link](http://doc.pytest.org/en/latest/skipping.html#mark-a-test-function-as-expected-to-fail) next to the travis-ci icon.

Your tests seem to fail due to a bad import. Run tests locally before pushing, as discussed in the [Contributing document](https://github.com/chriscz/pysorter/blob/master/CONTRIBUTING.md).

**Comment by toondegryse** [comment]
Hi Chriscz,

I haven't added an extra import and I can't really locate the bad import problem. For the testing, I suppose I need to compare my output to the expected output, yes? I don't see there being a use for @pytest.mark.xfail? 

Thanks,
Toon

**Comment by chriscz** [comment]
Your import used helper instead of pytest. What you should do is capture,
using the capsys fixture and then compare output.

There is an example in the source. Are you ruining your tests locally?
Because that will help you spot the error.

Let me know if you get stuck!
Thanks for helping out

**Comment by toondegryse** [comment]
Hi Chriscz,

I am stuck but I really want to do it. I am running the tests locally now. How can I produce output of a test, is that only possible way by using assert? If I use assert (like in the print version test), where does the output go? 

Thanks in advance,
Toon

**Comment by chriscz** [comment]
Hey Toon,

As in the print version test, your test function should have a single argument capsys, this will capture any outputs from the function.

To read the output you can exectue `out, err = capsys.readouterr()`
Here are some examples you can look at

- http://doc.pytest.org/en/latest/capture.html#accessing-captured-output-from-a-test-function
- http://stackoverflow.com/questions/20507601/writing-a-pytest-function-for-checking-the-output-on-console-stdout-in-python (here they use capfd, but you should use capsys)

When you use assert, it simply checks whether the condition holds,

**Comment by toondegryse** [comment]
Thanks Chriscz,

Thanks for your help. almost there. I have implemented the capsys part but it seems like I need `d` to create the temporary directories which I can't do if I use capsys. 

Toon

**Comment by chriscz** [comment]
Hey Toon, 
Yea, the annotation break's pytest injection. This is my fault.
The easiest way to get a temporary directory is to use this syntax:
```python
with TempDirectory() as d:
   # do something with d
```

**Comment by toondegryse** [comment]
Hi Chriscz,

This helps me a little but I can't seem to get around this OSError: Directory to organize does not exist or is a file: sourcefiles/

`def test_print_changes(capsys):
    with TempDirectory() as d:
        filetypes = {
            '.*\\.pdf$': 'docs/'
        }
        to_sort = 'sourcefiles/'
        to_make = ['file1.pdf']
        helper.initialize_dir(d, filetypes, helper.build_path_tree(to_make, to_sort))

        args = [to_sort, '-n']
        pysorter.main(args)

        out, err = capsys.readouterr()
        assert out == "move file sourcefiles/file1.pdf --> docs/file1.txt"`

Do you have input on this? I have tried a couple of ways around this issue but haven't been successful.
Thanks,
Toon

**Comment by chriscz** [comment]
Hi Toon,

Please push your WIP to your repository (work in progress) so I can better assist you. 
I'd suggest you debug a bit more and try and see why it's not working.

It would help a lot if you provide a stack trace / error traceback, because without that there's no way for me to tell what went wrong.

**Comment by toondegryse** [comment]
Hi Chriscz,

I have split the capsys from the tmpdir and that seemed to solve my problem. Please have a look.


Toon

**Comment by chriscz** [comment]
That's interesting. I'll have a look! Good job.

**Comment by chriscz** [comment]
Hi Toon, 

I have looked at your most recent pull request, but that does not have any of your changes on. 
Please push your changes to this PR.

**Comment by chriscz** [comment]
Hi toon, why do you keep opening new PR's? 
This one is the one you should be pushing too.

Anyway I'll look at the other one

**Comment by chriscz** [comment]
It happens when new code is added, that hasn't been fully tested, you can
look at the coverage report to see where some coverage is missing.

The CONTRIBUTING document discusses it. I hope to get around to your
submission within the next week.

**Comment by toondegryse** [comment]
Hi Chrisz, have you had a look and/or implemented this on your master branch?

Thanks,
Toon

**Comment by chriscz** [comment]
Hi Toon,

I have not got around to it yet. I'll let you know when I do.

Chris

**Comment by chriscz** [comment]
Hey Toon.

I'm working on the merge. 
I'll be pushing it soon.

**Comment by chriscz** [comment]
Merging completed

**Pull request closed without merging**
